Ignore type-less subclass with `misc` instead of `unreachable` ignore
The type is still reachable, `mypy` simply doesn't have type info hence
considers it as the `Any` type which shouldn't be subclassed:

    tests/test_tcp_models.py:206: error: Unused "type: ignore" comment
    tests/test_tcp_models.py:206: error: Class cannot subclass "TestCase" (has type "Any")  [misc]
    tests/test_tcp_models.py:206: note: Error code "misc" not covered by "type: ignore" comment